"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ChevronDown, Download, FileText, FolderOpen, Menu, Plus } from "lucide-react";
import { unicodeToBijoy } from "@abdalgolabs/ansi-unicode-converter";
import AppSidebar from "@/components/AppSidebar";
import useThesisTopicsState from "@/components/useThesisTopicsState";
import SeriesInput from "@/components/SeriesInput";
import CollapsibleTeacherCard from "@/components/CollapsibleTeacherCard";
import BengaliNoticeTextEditor, { bijoyNoticeToUnicode, SutonnyNoticeText, toSutonnyNumber } from "@/components/BengaliNoticeTextEditor";
import logoImage from "@/app/images/image_03.png";

const inputClass = "mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";
const storageKey = "ruet-thesis-final-defense-last-generated";
const computerDate = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const formatDate = (value: string) => { if (!value) return "-"; const [year, month, day] = value.split("-"); return toSutonnyNumber(`${day}/${month}/${year}`); };
const bengaliDays = ["রবিবার", "সোমবার", "মঙ্গলবার", "বুধবার", "বৃহস্পতিবার", "শুক্রবার", "শনিবার"];
const formatDay = (value: string) => value ? bengaliDays[new Date(`${value}T00:00:00`).getDay()] : "-";
const defaultHead = { name: "Rbve kvqjv kviwgb", designation: "wefvMxq cÖavb", department: "wewìs BwÄwbqvwis GÛ Kb÷ªvKkb g¨v‡bR‡g›U wefvM", university: "ivRkvnx cÖ‡KŠkj I cÖhyw³ wek¦we`¨vjq|" };
const defaultRows = [
  { id: "teacher-1", name: "জনাব শায়লা শারমিন", designation: "সহকারী অধ্যাপক, বিভাগীয় প্রধান, বিইসিএম বিভাগ।", rolls: "20120012, 20120020, 20120026, 20120028, 20120030" },
  { id: "teacher-2", name: "জনাব মেহেদী হাসান", designation: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", rolls: "20120008, 20120009, 20120016, 20120017, 20120030" },
  { id: "teacher-3", name: "জনাব ফারুক আব্দুল্লাহ", designation: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", rolls: "20120002, 20120007, 20120024, 20120025, 20120027" },
  { id: "teacher-4", name: "জনাব মোঃ আশরাফুল ইসলাম", designation: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", rolls: "20120001, 20120006, 20120019, 20120023, 20120029" },
  { id: "teacher-5", name: "জনাব মোঃ নূর আলম রিয়াদ", designation: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", rolls: "20120005, 20120014" },
  { id: "teacher-6", name: "জনাব মোঃ তৌফিক হাসান", designation: "প্রভাষক, বিইসিএম বিভাগ।", rolls: "20120003, 20120015" },
  { id: "teacher-7", name: "জনাব মোঃ মেহেদী হাসান গালিব", designation: "প্রভাষক, বিইসিএম বিভাগ।", rolls: "20120011, 20120013, 20120021" },
];
const createNotice = () => ({ memoNumber: `weBwmGg/${new Date().getFullYear()}/001`, date: computerDate(), series: "2020", defenseDate: computerDate(), period: "afternoon", time: "2.30" });
const defaultLayout = { header: { fontSize: 12, gapAfter: 0 }, meta: { fontSize: 18, gapAfter: 20 }, heading: { fontSize: 34, gapAfter: 28 }, body: { fontSize: 17, gapAfter: 12 }, table: { fontSize: 15, gapAfter: 28 }, signature: { fontSize: 17, gapAfter: 32 } };
const defaultWidths = { table: 100, schedule: 23, supervisor: 40, rolls: 37 };
type LayoutSection = keyof typeof defaultLayout;
const layoutLabels: Record<LayoutSection, string> = { header: "Header", meta: "Memo and date", heading: "Notice heading", body: "Notice body", table: "Defense table", signature: "Head signature" };
const noticeBodyStart = "GZØviv mswkøó mK‡ji AeMwZi Rb¨ Rvbv‡bv hv‡”Q †h, AÎ wefv‡Mi we.Gm.wm. BwÄwbqvwis 4_© el© we†Rvo †mwgóvi cixÿv-";
const noticeBodyBeforeCourse = " wmwiR) Gi QvÎ/QvÎx‡`i ";
const noticeBodyEnd = " কোর্সের থিসিস/প্রজেক্ট অগ্রগতির উপস্থাপন নিম্নবর্ণিত ছক মোতাবেক অনুষ্ঠিত হইবে।";

export default function ThesisFinalDefensePage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [thesisOpen, setThesisOpen] = useThesisTopicsState();
  const [notice, setNotice] = useState(createNotice);
  const [rows, setRows] = useState(defaultRows);
  const [departmentHeadName, setDepartmentHeadName] = useState<string>(defaultHead.name);
  const [layout, setLayout] = useState(defaultLayout);
  const [widths, setWidths] = useState(defaultWidths);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [pdfStatus, setPdfStatus] = useState("");
  const [customBody, setCustomBody] = useState("");
  const noticeRef = useRef<HTMLElement>(null);
  const parsedSeries = Number.parseInt(notice.series, 10);
  const examinationYear = Number.isNaN(parsedSeries) ? "—" : String(parsedSeries + 4);

  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) || "null"); if (!saved) return; if (saved.notice) setNotice(saved.notice); if (Array.isArray(saved.rows)) setRows(saved.rows); if (saved.departmentHeadName) setDepartmentHeadName(saved.departmentHeadName); if (saved.layout) setLayout({ ...saved.layout, header: { ...saved.layout.header, gapAfter: 0 } }); if (saved.widths) setWidths(saved.widths); } catch { /* Ignore invalid saved templates. */ } }, 0); return () => window.clearTimeout(timer); }, []);
  const update = (field: keyof ReturnType<typeof createNotice>, value: string) => setNotice((current) => ({ ...current, [field]: value }));
  const updateRow = (index: number, field: "name" | "designation" | "rolls", value: string) => setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row));
  const moveRow = (index: number, direction: -1 | 1) => setRows((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const updateLayout = (section: LayoutSection, field: "fontSize" | "gapAfter", value: number) => setLayout((current) => ({ ...current, [section]: { ...current[section], [field]: Math.max(0, value || 0) } }));
  const updateWidth = (field: keyof typeof defaultWidths, value: number) => setWidths((current) => ({ ...current, [field]: Math.max(1, Math.min(100, value || 1)) }));
  const generatePdf = async () => { const element = noticeRef.current; if (!element || isGeneratingPdf) return; setIsGeneratingPdf(true); setPdfStatus(""); try { await document.fonts.ready; await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))); const [{ toPng }, { jsPDF }] = await Promise.all([import("html-to-image"), import("jspdf")]); const image = await toPng(element, { backgroundColor: "#fff", pixelRatio: Math.max(2, window.devicePixelRatio || 1), cacheBust: true, width: element.scrollWidth, height: element.scrollHeight, style: { boxShadow: "none", maxWidth: "none" } }); const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4", compress: true }); pdf.addImage(image, "PNG", 0, 0, 210, 297, undefined, "FAST"); pdf.save(`Thesis-Final-defense-${notice.series || "notice"}.pdf`); localStorage.setItem(storageKey, JSON.stringify({ notice, rows, departmentHeadName, layout, widths })); setPdfStatus("PDF generated and template saved."); } catch (error) { console.error(error); setPdfStatus("Unable to generate PDF."); } finally { setIsGeneratingPdf(false); } };

  return <div className="mx-auto flex min-h-screen w-full max-w-[1800px] bg-slate-100 text-slate-900"><AppSidebar mobileOpen={mobileOpen} onClose={() => setMobileOpen(false)} /><main className="min-w-0 flex-1">
    <header className="sticky top-0 z-40 flex h-[72px] items-center gap-4 border-b bg-white px-4 shadow-sm sm:px-6"><button type="button" onClick={() => setMobileOpen(true)} className="rounded-lg p-2 lg:hidden" aria-label="Open navigation"><Menu className="h-6 w-6" /></button><div><h1 className="text-xl font-bold text-[#102555]">Official Files</h1><p className="text-sm text-slate-500">Prepare and preview departmental documents</p></div></header>
    <div className="grid gap-5 p-4 sm:p-6 xl:grid-cols-[240px_minmax(320px,390px)_minmax(600px,1fr)]">
      <aside className="overflow-hidden rounded-xl border bg-white shadow-sm xl:sticky xl:top-[96px] xl:self-start"><div className="border-b px-4 py-4"><h2 className="font-semibold text-[#102555]">Topics and files</h2><p className="mt-1 text-xs text-slate-500">Select a document to prepare</p></div><div className="p-3"><button type="button" onClick={() => setThesisOpen((open) => !open)} className="flex w-full items-center gap-2 rounded-lg bg-indigo-50 px-3 py-2.5 text-left font-semibold text-indigo-800" aria-expanded={thesisOpen}><ChevronDown className={`h-4 w-4 transition-transform ${thesisOpen ? "" : "-rotate-90"}`} /><FolderOpen className="h-5 w-5" />Thesis<span className="ml-auto text-[10px] font-medium">{thesisOpen ? "Minimize" : "Expand"}</span></button>{thesisOpen && <><Link href="/files" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Thesis Distribution</Link><Link href="/files/thesis-pre-defense" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Thesis Pre-defense Student (1)</Link><Link href="/files/thesis-final-defense" className="mt-1 flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2.5 text-sm text-white shadow-sm" aria-current="page"><FileText className="ml-5 h-4 w-4" />Thesis Pre-defense Student (2)</Link><Link href="/files/pre-defense-teacher" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Pre-defense Teacher</Link><Link href="/files/thesis-final-defense-student" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Thesis Final Defense Student</Link><Link href="/files/thesis-final-defense-teacher" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Thesis Final Defense Teacher</Link><Link href="/files/external" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />External</Link><Link href="/files/attendance" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Attendance</Link><Link href="/files/internal-external" className="mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700"><FileText className="ml-5 h-4 w-4" />Internal-External</Link></>}</div></aside>
      <section className="rounded-xl border bg-white shadow-sm xl:sticky xl:top-[96px] xl:self-start"><div className="border-b px-5 py-4"><h2 className="font-semibold text-[#102555]">Thesis Pre-defense Student (2)</h2><p className="text-xs text-slate-500">Enter the final-defense information</p></div><div className="max-h-[calc(100vh-120px)] space-y-4 overflow-y-auto p-5">
        <label className="block text-sm font-medium">Memo number<input className={`${inputClass} font-['SutonnyMJ'] text-lg`} value={notice.memoNumber} onChange={(event) => update("memoNumber", event.target.value)} /></label><label className="block text-sm font-medium">Notice date<input type="date" className={inputClass} value={notice.date} onChange={(event) => update("date", event.target.value)} /></label><label className="block text-sm font-medium">Series<SeriesInput value={notice.series} onChange={(value) => update("series", value)} inputClassName={inputClass} /></label>
        <div className="grid grid-cols-3 gap-2"><label className="text-sm font-medium">Defense date<input type="date" className={inputClass} value={notice.defenseDate} onChange={(event) => update("defenseDate", event.target.value)} /></label><label className="text-sm font-medium">Period<select className={inputClass} value={notice.period} onChange={(event) => update("period", event.target.value)}><option value="morning">সকাল</option><option value="afternoon">দুপুর</option></select></label><label className="text-sm font-medium">Time<input style={{ fontFamily: '"Times New Roman", serif' }} className={inputClass} value={notice.time} onChange={(event) => update("time", event.target.value)} /></label></div>
        <div className="border-t pt-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Supervisors</h3><p className="text-xs text-slate-500">Avro/Bengali input and assigned rolls</p></div><button type="button" onClick={() => setRows((current) => [...current, { id: crypto.randomUUID(), name: "", designation: "প্রভাষক, বিইসিএম বিভাগ।", rolls: "" }])} className="inline-flex items-center gap-1 rounded-md border border-indigo-200 px-2 py-1.5 text-xs font-semibold text-indigo-700"><Plus className="h-3.5 w-3.5" />Add</button></div><div className="mt-3 space-y-3">{rows.map((row, index) => <CollapsibleTeacherCard key={row.id} name={row.name} index={index} isFirst={index === 0} isLast={index === rows.length - 1} onMoveUp={() => moveRow(index, -1)} onMoveDown={() => moveRow(index, 1)} onDelete={rows.length === 1 ? undefined : () => setRows((current) => current.filter((_, rowIndex) => rowIndex !== index))}><label className="block text-xs">Name<input lang="bn" style={{ fontFamily: '"Nirmala UI", Arial, sans-serif' }} className={inputClass} value={row.name} onChange={(event) => updateRow(index, "name", event.target.value)} /></label><label className="mt-2 block text-xs">Designation and department<input lang="bn" style={{ fontFamily: '"Nirmala UI", Arial, sans-serif' }} className={inputClass} value={row.designation} onChange={(event) => updateRow(index, "designation", event.target.value)} /></label><label className="mt-2 block text-xs">Roll numbers (English input)<textarea rows={2} inputMode="numeric" style={{ fontFamily: '"Times New Roman", Times, serif' }} className={inputClass} value={row.rolls} onChange={(event) => updateRow(index, "rolls", event.target.value)} /></label></CollapsibleTeacherCard>)}</div></div>
        <div className="border-t pt-4"><h3 className="mb-2 text-sm font-semibold">Layout controls</h3><div className="space-y-2">{(Object.keys(layoutLabels) as LayoutSection[]).map((section) => <div key={section} className="grid grid-cols-[1fr_76px_76px] items-end gap-2 rounded-lg border bg-slate-50 p-2.5"><span className="self-center text-xs font-semibold">{layoutLabels[section]}</span><label className="text-[10px]">Font<input type="number" step="0.5" value={layout[section].fontSize} onChange={(event) => updateLayout(section, "fontSize", Number(event.target.value))} className="mt-1 w-full rounded-md border px-2 py-1.5" /></label><label className="text-[10px]">Gap<input type="number" value={layout[section].gapAfter} onChange={(event) => updateLayout(section, "gapAfter", Number(event.target.value))} className="mt-1 w-full rounded-md border px-2 py-1.5" /></label></div>)}</div></div>
        <div className="rounded-lg border bg-slate-50 p-3"><h3 className="text-xs font-semibold">Table width controls</h3><div className="mt-2 grid grid-cols-2 gap-2">{([['table','Overall'],['schedule','Date/time'],['supervisor','Supervisor'],['rolls','Rolls']] as const).map(([field,label]) => <label key={field} className="text-[10px]">{label} (%)<input type="number" value={widths[field]} onChange={(event) => updateWidth(field, Number(event.target.value))} className="mt-1 w-full rounded-md border px-2 py-1.5" /></label>)}</div></div>
        <BengaliNoticeTextEditor value={customBody} onChange={setCustomBody} defaultValue={bijoyNoticeToUnicode(`${noticeBodyStart}${examinationYear} (${notice.series || "—"}${noticeBodyBeforeCourse}BECM 4000 (Project and Thesis)${noticeBodyEnd}`)} />
        <label className="block text-sm font-medium">Department head name<input className={`${inputClass} font-['SutonnyMJ'] text-lg`} value={departmentHeadName} onChange={(event) => setDepartmentHeadName(event.target.value)} /></label>
      </div></section>
      <section className="min-w-0 rounded-xl border bg-slate-300 shadow-sm"><div className="flex items-center justify-between border-b bg-white px-5 py-3"><div><h2 className="font-semibold">Preview</h2><p className="text-xs text-slate-500">Live A4 document preview</p></div><div className="flex items-center gap-3">{pdfStatus && <span className="text-xs text-emerald-700">{pdfStatus}</span>}<button type="button" onClick={generatePdf} disabled={isGeneratingPdf} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-indigo-400"><Download className="h-4 w-4" />{isGeneratingPdf ? "Generating…" : "Generate PDF"}</button></div></div><div className="overflow-auto p-4 sm:p-6">
        <article ref={noticeRef} lang="bn" className="file-print-document mx-auto min-h-[1123px] w-[794px] max-w-full bg-white px-[6%] py-12 text-black shadow-xl">
          <header className="notice-header w-full border-b border-black pb-1"><p style={{ fontSize: layout.header.fontSize * .8 }} className="text-center font-semibold leading-none text-[#2f78b7]">“Heaven&apos;s Light is Our Guide”</p><h2 style={{ fontSize: layout.header.fontSize * 1.7 }} className="mt-1 text-center font-bold leading-none text-[#145365]">Rajshahi University of Engineering &amp; Technology</h2><div className="mt-1 grid w-full grid-cols-[minmax(0,1fr)_68px_minmax(0,1fr)] items-center gap-3"><div style={{ fontSize: layout.header.fontSize }} className="header-bangla text-right leading-[1.25]"><p className="font-bold text-[#174e72]">বিভাগীয় প্রধানের কার্যালয়</p><p className="whitespace-nowrap font-bold text-[#8b2525]">বিল্ডিং ইঞ্জিনিয়ারিং এন্ড কনস্ট্রাকশন ম্যানেজমেন্ট বিভাগ</p><p className="font-semibold text-[#8b4a11]">রাজশাহী-৬২০৪, বাংলাদেশ</p></div><Image src={logoImage} alt="RUET logo" className="mx-auto h-[62px] w-[62px] object-contain" priority /><div style={{ fontSize: layout.header.fontSize }} className="text-left leading-[1.15]"><p style={{ fontSize: layout.header.fontSize * 1.3 }} className="font-bold text-[#174e72]">Office of the Head</p><p className="font-bold text-[#9b2929]">Building Engineering &amp; Construction Management</p><p className="font-semibold text-[#8b4a11]">Rajshahi-6204, Bangladesh</p></div></div><p style={{ fontSize: layout.header.fontSize * .9 }} className="mt-0.5 text-center font-semibold leading-none">Phone &amp; Fax : +88 0258886742, &nbsp; E-Mail : <span className="text-blue-700 underline">head@becm.ruet.ac.bd</span> , &nbsp; Website : www.becm.ruet.ac.bd</p></header>
          <div style={{ marginTop: layout.header.gapAfter, fontSize: layout.meta.fontSize }} className="flex justify-between"><p>¯§viK bs- {notice.memoNumber || "-"}</p><p>ZvwiLt {formatDate(notice.date)} wLªt|</p></div><h1 style={{ marginTop: layout.meta.gapAfter, fontSize: layout.heading.fontSize }} className="text-center">-t weÁwß t-</h1>
          <p style={{ marginTop: layout.heading.gapAfter, fontSize: layout.body.fontSize }} className="text-justify leading-[1.65]">{customBody.trim() ? <SutonnyNoticeText text={customBody} /> : <>{noticeBodyStart}{examinationYear === "—" ? examinationYear : toSutonnyNumber(examinationYear)} ({notice.series ? toSutonnyNumber(notice.series) : "—"}{noticeBodyBeforeCourse}<span className="notice-times">BECM 4000 (Project and Thesis)</span>{unicodeToBijoy(noticeBodyEnd)}</>}</p>
          <table style={{ marginTop: layout.body.gapAfter, fontSize: layout.table.fontSize, width: `${widths.table}%`, marginInline: "auto" }} className="table-fixed border-collapse text-center leading-[1.3]"><thead><tr><th rowSpan={2} style={{ width: `${widths.schedule}%` }} className="border border-black p-1">{unicodeToBijoy("তারিখ ও সময়")}</th><th colSpan={2} className="border border-black p-1">{unicodeToBijoy("ছাত্র-ছাত্রীদের সুপারভাইজার ও রোল নম্বর")}</th></tr><tr><th style={{ width: `${widths.supervisor}%` }} className="border border-black p-1">{unicodeToBijoy("সুপারভাইজার")}</th><th style={{ width: `${widths.rolls}%` }} className="border border-black p-1">{unicodeToBijoy("রোল নম্বর")}</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id}>{index === 0 && <td rowSpan={rows.length} className="border border-black p-2 align-middle">{formatDate(notice.defenseDate)} wLª.<br /><br />({unicodeToBijoy(formatDay(notice.defenseDate))})<br /><br />{unicodeToBijoy(notice.period === "afternoon" ? "দুপুর" : "সকাল")} ({notice.time ? toSutonnyNumber(notice.time) : "—"}) NwUKv</td>}<td className="border border-black px-2 py-1 text-left">{unicodeToBijoy(row.name)}<br />{unicodeToBijoy(row.designation)}</td><td className="whitespace-pre-wrap border border-black px-2 py-1">{row.rolls}</td></tr>)}</tbody></table>
          <div style={{ marginTop: layout.table.gapAfter }} className="notice-times text-[16px] leading-[1.5]"><div className="mx-auto grid w-fit grid-cols-[auto_1fr] gap-x-3 text-left"><p><u>Topics to be included in the slide:</u></p><div><p>1. Titel Page&nbsp; 2. Thesis Background&nbsp; 3. Literature Survey</p><p>4. Objectives&nbsp; 5. Expected Outcome</p></div></div><p className="mt-4 text-center"><u>Time:</u>&nbsp; 5.00 min. Presentation, 2.00 min question &amp; answer.</p></div>
          <div style={{ marginTop: 48, marginBottom: layout.signature.gapAfter, fontSize: layout.signature.fontSize }} className="ml-auto mr-2 w-[300px] text-center leading-[1.25]"><p style={{ fontSize: layout.signature.fontSize + 3 }} className="font-bold">({departmentHeadName.trim() || defaultHead.name})</p><p>{defaultHead.designation}</p><p>{defaultHead.department}</p><p>{defaultHead.university}</p></div>
        </article>
      </div></section>
    </div>
  </main></div>;
}

