"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ChevronDown, Download, FileText, FolderOpen, Menu, Plus, Save } from "lucide-react";
import { unicodeToBijoy } from "@abdalgolabs/ansi-unicode-converter";
import AppSidebar from "@/components/AppSidebar";
import useThesisTopicsState from "@/components/useThesisTopicsState";
import SeriesInput from "@/components/SeriesInput";
import CollapsibleTeacherCard from "@/components/CollapsibleTeacherCard";
import BengaliNoticeTextEditor, { SutonnyNoticeText, toSutonnyNumber } from "@/components/BengaliNoticeTextEditor";
import logoImage from "@/app/images/image_03.png";
import { printNotice } from "@/lib/printNotice";

const inputClass = "mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";
const bengaliInputStyle = { fontFamily: '"Nirmala UI", Arial, sans-serif' };
const storageKey = "ruet-internal-external-last-generated-v2";
const computerDate = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const formatDate = (value: string) => { if (!value) return "-"; const [year, month, day] = value.split("-"); return toSutonnyNumber(`${day}/${month}/${year}`); };
const defaultHead = { name: "Rbve kvqjv kviwgb", designation: "wefvMxq cÖavb", department: "wewìs BwÄwbqvwis GÛ Kb÷ªvKkb g¨v‡bR‡g›U wefvM", university: "ivRkvnx cÖ‡KŠkj I cÖhyw³ wek¦we`¨vjq|" };
const defaultRows = [
  { id: "pair-1", internalName: "জনাব রাজিবুল আওয়াল", internalDetails: "সহকারী অধ্যাপক, বিভাগীয় প্রধান, বিইসিএম বিভাগ।", internalRolls: "20120111, 20120120, 20120126, 17120120", externalName: "জনাব শায়লা শারমিন", externalDetails: "সহকারী অধ্যাপক, বিভাগীয় প্রধান, বিইসিএম বিভাগ।", externalRolls: "20120008, 20120009, 20120016, 20120017" },
  { id: "pair-2", internalName: "জনাব মেহেদী হাসান", internalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", internalRolls: "20120008, 20120009, 20120016, 20120017, 20120030", externalName: "জনাব মেহেদী হাসান", externalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", externalRolls: "20120012, 20120026, 20120028, 17120120" },
  { id: "pair-3", internalName: "জনাব ফারুক আব্দুল্লাহ", internalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", internalRolls: "20120002, 20120007, 20120024, 20120025, 20120027", externalName: "জনাব ফারুক আব্দুল্লাহ", externalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", externalRolls: "20120001, 20120019, 20120021, 20120023" },
  { id: "pair-4", internalName: "জনাব মোঃ আশরাফুল ইসলাম", internalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", internalRolls: "20120001, 20120006, 20120019, 20120023, 20120029", externalName: "জনাব মোঃ আশরাফুল ইসলাম", externalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", externalRolls: "20120002, 20120007, 20120015, 20120025" },
  { id: "pair-5", internalName: "জনাব মোঃ নূর আলম রিয়াদ", internalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", internalRolls: "20120005, 20120014, 20120030", externalName: "জনাব মোঃ নূর আলম রিয়াদ", externalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", externalRolls: "20120003, 20120006, 20120028, 20120030" },
  { id: "pair-6", internalName: "জনাব মোঃ তৌফিক হাসান", internalDetails: "প্রভাষক, বিইসিএম বিভাগ।", internalRolls: "20120011, 20120013, 20120014", externalName: "জনাব মোঃ তৌফিক হাসান", externalDetails: "প্রভাষক, বিইসিএম বিভাগ।", externalRolls: "20120011, 20120013, 20120014, 20120029" },
  { id: "pair-7", internalName: "জনাব মোঃ মেহেদী হাসান গালিব", internalDetails: "প্রভাষক, বিইসিএম বিভাগ।", internalRolls: "20120003, 20120015", externalName: "জনাব মোঃ মেহেদী হাসান গালিব", externalDetails: "প্রভাষক, বিইসিএম বিভাগ।", externalRolls: "20120005, 20120013, 20120014" },
];
const createNotice = () => ({ memoNumber: `weBwmGg/${new Date().getFullYear()}/001`, date: computerDate(), series: "2020" });
const defaultLayout = { header: { fontSize: 12, gapAfter: 0 }, meta: { fontSize: 18, gapAfter: 8 }, heading: { fontSize: 24, gapAfter: 8 }, body: { fontSize: 15, gapAfter: 11 }, table: { fontSize: 14, gapAfter: 75 }, signature: { fontSize: 15.5, gapAfter: 32 } };
const defaultWidths = { table: 100, serial: 7, member: 36, rolls: 40 };
type LayoutSection = keyof typeof defaultLayout;
const layoutLabels: Record<LayoutSection, string> = { header: "Header", meta: "Memo and date", heading: "Notice heading", body: "Notice body", table: "Committee table", signature: "Head signature" };

export default function InternalExternalPage() {
  const [mobileOpen, setMobileOpen] = useState(false); const [thesisOpen, setThesisOpen] = useThesisTopicsState();
  const [notice, setNotice] = useState(createNotice); const [rows, setRows] = useState(defaultRows);
  const [departmentHeadName, setDepartmentHeadName] = useState<string>(defaultHead.name); const [layout, setLayout] = useState(defaultLayout); const [widths, setWidths] = useState(defaultWidths);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false); const [pdfStatus, setPdfStatus] = useState(""); const noticeRef = useRef<HTMLElement>(null);
  const [customBody, setCustomBody] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) || "null"); if (!saved) return; if (saved.notice) setNotice(saved.notice); if (Array.isArray(saved.rows)) setRows(saved.rows); if (saved.departmentHeadName) setDepartmentHeadName(saved.departmentHeadName); if (saved.layout) setLayout(saved.layout); if (saved.widths) setWidths(saved.widths); if (typeof saved.customBody === "string") setCustomBody(saved.customBody); } catch { /* Ignore invalid templates. */ } }, 0); return () => window.clearTimeout(timer); }, []);
  const update = (field: keyof ReturnType<typeof createNotice>, value: string) => setNotice((current) => ({ ...current, [field]: value }));
  const updateRow = (index: number, field: "internalName" | "internalDetails" | "internalRolls" | "externalName" | "externalDetails" | "externalRolls", value: string) => setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row));
  const moveRow = (index: number, direction: -1 | 1) => setRows((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const reordered = [...current]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; return reordered; });
  const updateLayout = (section: LayoutSection, field: "fontSize" | "gapAfter", value: number) => setLayout((current) => ({ ...current, [section]: { ...current[section], [field]: Math.max(0, value || 0) } }));
  const updateWidth = (field: keyof typeof defaultWidths, value: number) => setWidths((current) => ({ ...current, [field]: Math.max(1, Math.min(100, value || 1)) }));
  const generatePdf = async () => { const element = noticeRef.current; if (!element || isGeneratingPdf) return; setIsGeneratingPdf(true); setPdfStatus(""); try { await document.fonts.ready; await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))); const [{ toPng }, { jsPDF }] = await Promise.all([import("html-to-image"), import("jspdf")]); const image = await toPng(element, { backgroundColor: "#fff", pixelRatio: Math.max(2, window.devicePixelRatio || 1), cacheBust: true, width: element.scrollWidth, height: element.scrollHeight, style: { boxShadow: "none", maxWidth: "none" } }); const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4", compress: true }); pdf.addImage(image, "PNG", 0, 0, 210, 297, undefined, "FAST"); pdf.save("Internal-External.pdf"); localStorage.setItem(storageKey, JSON.stringify({ notice, rows, departmentHeadName, layout, widths })); setPdfStatus("PDF generated and template saved."); } catch (error) { console.error(error); setPdfStatus("Unable to generate PDF."); } finally { setIsGeneratingPdf(false); } };

  const fileLink = "mt-1 flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-700 hover:bg-indigo-50";
  return <div className="mx-auto flex min-h-screen w-full max-w-[1800px] bg-slate-100 text-slate-900"><AppSidebar mobileOpen={mobileOpen} onClose={() => setMobileOpen(false)} /><main className="min-w-0 flex-1">
    <header className="sticky top-0 z-40 flex h-[72px] items-center gap-4 border-b bg-white px-4 shadow-sm sm:px-6"><button type="button" onClick={() => setMobileOpen(true)} className="rounded-lg p-2 lg:hidden" aria-label="Open navigation"><Menu className="h-6 w-6" /></button><div><h1 className="text-xl font-bold text-[#102555]">Official Files</h1><p className="text-sm text-slate-500">Prepare and preview departmental documents</p></div></header>
    <div className="grid gap-5 p-4 sm:p-6 xl:grid-cols-[240px_minmax(320px,390px)_minmax(600px,1fr)]">
      <aside className="overflow-hidden rounded-xl border bg-white shadow-sm xl:sticky xl:top-[96px] xl:self-start"><div className="border-b px-4 py-4"><h2 className="font-semibold text-[#102555]">Topics and files</h2><p className="text-xs text-slate-500">Select a document to prepare</p></div><div className="p-3"><button type="button" onClick={() => setThesisOpen((open) => !open)} className="flex w-full items-center gap-2 rounded-lg bg-indigo-50 px-3 py-2.5 text-left font-semibold text-indigo-800" aria-expanded={thesisOpen}><ChevronDown className={`h-4 w-4 ${thesisOpen ? "" : "-rotate-90"}`} /><FolderOpen className="h-5 w-5" />Thesis<span className="ml-auto text-[10px] font-medium">{thesisOpen ? "Minimize" : "Expand"}</span></button>{thesisOpen && <><Link href="/files" className={fileLink}><FileText className="ml-5 h-4 w-4" />Thesis Distribution</Link><Link href="/files/thesis-pre-defense" className={fileLink}><FileText className="ml-5 h-4 w-4" />Thesis Pre-defense Student (1)</Link><Link href="/files/thesis-final-defense" className={fileLink}><FileText className="ml-5 h-4 w-4" />Thesis Pre-defense Student (2)</Link><Link href="/files/pre-defense-teacher" className={fileLink}><FileText className="ml-5 h-4 w-4" />Pre-defense Teacher</Link><Link href="/files/thesis-final-defense-student" className={fileLink}><FileText className="ml-5 h-4 w-4" />Thesis Final Defense Student</Link><Link href="/files/thesis-final-defense-teacher" className={fileLink}><FileText className="ml-5 h-4 w-4" />Thesis Final Defense Teacher</Link><Link href="/files/external" className={fileLink}><FileText className="ml-5 h-4 w-4" />External</Link><Link href="/files/attendance" className={fileLink}><FileText className="ml-5 h-4 w-4" />Attendance</Link><Link href="/files/internal-external" className="mt-1 flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2.5 text-sm text-white shadow-sm" aria-current="page"><FileText className="ml-5 h-4 w-4" />Internal-External</Link></>}</div></aside>
      <section className="rounded-xl border bg-white shadow-sm xl:sticky xl:top-[96px] xl:self-start"><div className="border-b px-5 py-4"><h2 className="font-semibold text-[#102555]">Internal-External</h2><p className="text-xs text-slate-500">Configure committee member pairs</p></div><div className="max-h-[calc(100vh-120px)] space-y-4 overflow-y-auto p-5">
        <label className="block text-sm font-medium">Memo number<input className={`${inputClass} font-['SutonnyMJ'] text-lg`} value={notice.memoNumber} onChange={(event) => update("memoNumber", event.target.value)} /></label><label className="block text-sm font-medium">Notice date<input type="date" className={inputClass} value={notice.date} onChange={(event) => update("date", event.target.value)} /></label><label className="block text-sm font-medium">Series<SeriesInput value={notice.series} onChange={(value) => update("series", value)} inputClassName={inputClass} /></label>
        <BengaliNoticeTextEditor value={customBody} onChange={setCustomBody} defaultValue={`এতদ্বারা সংশ্লিষ্ট সকলের অবগতির জন্য জানানো যাচ্ছে যে, অত্র বিভাগের ৪র্থ বর্ষ জোড় সেমিস্টার (${notice.series || "—"} সিরিজ) এর BECM 4000 (Project and Thesis) কোর্সের পরিচালনার জন্য অভ্যন্তরীণ ও বহিঃ সদস্য কমিটি নিম্নলিখিতভাবে গঠন করা হলো।`} />
        <div className="border-t pt-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Committee rows</h3><p className="text-xs text-slate-500">Bengali member details and English roll inputs</p></div><button type="button" onClick={() => setRows((current) => [...current, { id: crypto.randomUUID(), internalName: "", internalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", internalRolls: "", externalName: "", externalDetails: "সহকারী অধ্যাপক, বিইসিএম বিভাগ।", externalRolls: "" }])} className="inline-flex items-center gap-1 rounded-md border border-indigo-200 px-2 py-1.5 text-xs font-semibold text-indigo-700"><Plus className="h-3.5 w-3.5" />Add row</button></div><div className="mt-3 space-y-3">{rows.map((row, index) => <CollapsibleTeacherCard key={row.id} name={row.internalName} index={index} isFirst={index === 0} isLast={index === rows.length - 1} onMoveUp={() => moveRow(index, -1)} onMoveDown={() => moveRow(index, 1)} onDelete={rows.length === 1 ? undefined : () => setRows((current) => current.filter((_, rowIndex) => rowIndex !== index))}>{([['internalName','Internal member name',false],['internalDetails','Internal designation/department',false],['internalRolls','Internal student rolls',true],['externalName','External member name',false],['externalDetails','External designation/department',false],['externalRolls','External student rolls',true]] as const).map(([field,label,isRoll]) => <label key={field} className="mt-2 block text-xs">{label}<input lang={isRoll ? "en" : "bn"} inputMode={isRoll ? "numeric" : undefined} style={isRoll ? { fontFamily: '"Times New Roman", Times, serif' } : bengaliInputStyle} className={inputClass} value={row[field]} onChange={(event) => updateRow(index, field, event.target.value)} /></label>)}</CollapsibleTeacherCard>)}</div></div>
        <div className="border-t pt-4"><h3 className="mb-2 text-sm font-semibold">Layout controls</h3><div className="space-y-2">{(Object.keys(layoutLabels) as LayoutSection[]).map((section) => <div key={section} className="grid grid-cols-[1fr_76px_76px] items-end gap-2 rounded-lg border bg-slate-50 p-2.5"><span className="self-center text-xs font-semibold">{layoutLabels[section]}</span><label className="text-[10px]">Font<input type="number" step="0.5" value={layout[section].fontSize} onChange={(event) => updateLayout(section,"fontSize",Number(event.target.value))} className="mt-1 w-full rounded border px-2 py-1.5" /></label><label className="text-[10px]">Gap<input type="number" value={layout[section].gapAfter} onChange={(event) => updateLayout(section,"gapAfter",Number(event.target.value))} className="mt-1 w-full rounded border px-2 py-1.5" /></label></div>)}</div></div>
        <div className="rounded-lg border bg-slate-50 p-3"><h3 className="text-xs font-semibold">Table width controls</h3><div className="mt-2 grid grid-cols-2 gap-2">{([['table','Overall'],['serial','Serial'],['member','Member details'],['rolls','Student rolls']] as const).map(([field,label]) => <label key={field} className="text-[10px]">{label} (%)<input type="number" value={widths[field]} onChange={(event) => updateWidth(field,Number(event.target.value))} className="mt-1 w-full rounded border px-2 py-1.5" /></label>)}</div></div>
        <label className="block text-sm font-medium">Department head name<input className={`${inputClass} font-['SutonnyMJ'] text-lg`} value={departmentHeadName} onChange={(event) => setDepartmentHeadName(event.target.value)} /></label>
      </div></section>
      <section className="min-w-0 rounded-xl border bg-slate-300 shadow-sm"><div className="flex items-center justify-between border-b bg-white px-5 py-3"><div><h2 className="font-semibold">Preview</h2><p className="text-xs text-slate-500">Live A4 document preview</p></div><div className="flex items-center gap-3">{pdfStatus && <span className="text-xs text-emerald-700">{pdfStatus}</span>}<button type="button" onClick={printNotice} className="inline-flex items-center gap-2 rounded-lg border border-indigo-200 bg-white px-4 py-2 text-sm font-semibold text-indigo-700 hover:bg-indigo-50"><Save className="h-4 w-4" />Save as PDF</button><button type="button" onClick={generatePdf} disabled={isGeneratingPdf} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-indigo-400"><Download className="h-4 w-4" />{isGeneratingPdf ? "Generating…" : "Generate PDF"}</button></div></div><div className="overflow-auto p-4 sm:p-6">
        <article ref={noticeRef} lang="bn" className="file-print-document mx-auto min-h-[1123px] w-[794px] max-w-full bg-white px-[6%] py-12 text-black shadow-xl">
          <header className="notice-header w-full border-b border-black pb-1"><p style={{ fontSize: layout.header.fontSize * .8 }} className="text-center font-semibold leading-none text-[#2f78b7]">“Heaven&apos;s Light is Our Guide”</p><h2 style={{ fontSize: layout.header.fontSize * 1.7 }} className="mt-1 text-center font-bold leading-none text-[#145365]">Rajshahi University of Engineering &amp; Technology</h2><div className="mt-1 grid w-full grid-cols-[minmax(0,1fr)_68px_minmax(0,1fr)] items-center gap-3"><div style={{ fontSize: layout.header.fontSize }} className="header-bangla text-right leading-[1.25]"><p className="font-bold text-[#174e72]">wefvMxq cÖav‡bi Kvh©vjq</p><p className="whitespace-nowrap font-bold text-[#8b2525]">wewìs BwÄwbqvwis GÛ KÝUªvKkb g¨v‡bR‡g›U wefvM</p><p className="font-semibold text-[#8b4a11]">ivRkvnx-6204,evsjv‡`k</p></div><Image src={logoImage} alt="RUET logo" className="mx-auto h-[62px] w-[62px] object-contain" priority /><div style={{ fontSize: layout.header.fontSize }} className="text-left leading-[1.15]"><p style={{ fontSize: layout.header.fontSize * 1.3 }} className="font-bold text-[#174e72]">Office of the Head</p><p className="font-bold text-[#9b2929]">Building Engineering &amp; Construction Management</p><p className="font-semibold text-[#8b4a11]">Rajshahi-6204, Bangladesh</p></div></div><p style={{ fontSize: layout.header.fontSize * .9 }} className="mt-0.5 text-center font-semibold leading-none">Phone &amp; Fax : +88 0258886742, &nbsp; E-Mail : <span className="text-blue-700 underline">head@becm.ruet.ac.bd</span> , &nbsp; Website : www.becm.ruet.ac.bd</p></header>
          <div style={{ marginTop: layout.header.gapAfter, fontSize: layout.meta.fontSize }} className="flex justify-between"><p>¯§viK bs- {notice.memoNumber || "-"}</p><p>ZvwiLt {formatDate(notice.date)} wLªt|</p></div><h1 style={{ marginTop: layout.meta.gapAfter, fontSize: layout.heading.fontSize }} className="text-center">-t weÁwß t-</h1>
          <p style={{ marginTop: layout.heading.gapAfter, fontSize: layout.body.fontSize }} className="text-justify leading-[1.7]">{customBody.trim() ? <SutonnyNoticeText text={customBody} /> : <>{unicodeToBijoy("এতদ্বারা সংশ্লিষ্ট সকলের অবগতির জন্য জানানো যাচ্ছে যে, অত্র বিভাগের ৪র্থ বর্ষ জোড় সেমিস্টার (")}{notice.series ? toSutonnyNumber(notice.series) : "—"}{unicodeToBijoy(" সিরিজ) এর ")}<span className="notice-times">BECM 4000 (Project and Thesis)</span>{unicodeToBijoy(" কোর্সের পরিচালনার জন্য অভ্যন্তরীণ ও বহিঃ সদস্য কমিটি নিম্নলিখিতভাবে গঠন করা হলো।")}</>}</p>
          <table style={{ marginTop: layout.body.gapAfter, fontSize: layout.table.fontSize, width: `${widths.table}%`, marginInline: "auto" }} className="table-fixed border-collapse leading-[1.4]"><thead><tr><th style={{ width: `${widths.serial}%` }} className="border border-black p-1 text-center">{unicodeToBijoy("ক্রমিক নং")}</th><th style={{ width: `${widths.member}%` }} className="border border-black p-1 text-center">{unicodeToBijoy("শিক্ষকের নাম, পদবী ও বিভাগ (অভ্যন্তরীণ সদস্য)")}</th><th style={{ width: `${widths.rolls}%` }} className="border border-black p-1 text-center">{unicodeToBijoy("শিক্ষার্থীদের রোল নং")}</th></tr></thead><tbody>{rows.map((row,index) => <tr key={row.id}><td className="border border-black p-1 text-center">{index + 1}.</td><td className="border border-black px-2 py-1">{unicodeToBijoy(row.internalName)}{index === 0 ? <br /> : ", "}{unicodeToBijoy(row.internalDetails)}</td><td className="whitespace-pre-wrap border border-black px-2 py-1 text-center">{row.internalRolls}</td></tr>)}</tbody></table>
          <table style={{ marginTop: 28, fontSize: layout.table.fontSize, width: `${widths.table}%`, marginInline: "auto" }} className="table-fixed border-collapse leading-[1.4]"><thead><tr><th style={{ width: `${widths.serial}%` }} className="border border-black p-1 text-center">{unicodeToBijoy("ক্রমিক নং")}</th><th style={{ width: `${widths.member}%` }} className="border border-black p-1 text-center">{unicodeToBijoy("শিক্ষকের নাম, পদবী ও বিভাগ (বহিঃ সদস্য)")}</th><th style={{ width: `${widths.rolls}%` }} className="border border-black p-1 text-center">{unicodeToBijoy("শিক্ষার্থীদের রোল নং")}</th></tr></thead><tbody>{rows.map((row,index) => <tr key={row.id}><td className="border border-black p-1 text-center">{index + 1}.</td><td className="border border-black px-2 py-1">{unicodeToBijoy(row.externalName)}{index === 0 ? <br /> : ", "}{unicodeToBijoy(row.externalDetails)}</td><td className="whitespace-pre-wrap border border-black px-2 py-1 text-center">{row.externalRolls}</td></tr>)}</tbody></table>
          <div style={{ marginTop: layout.table.gapAfter, marginBottom: layout.signature.gapAfter, fontSize: layout.signature.fontSize }} className="ml-auto mr-2 w-[300px] text-center leading-[1.25]"><p style={{ fontSize: layout.signature.fontSize + 3 }} className="font-bold">({departmentHeadName.trim() || defaultHead.name})</p><p>{defaultHead.designation}</p><p>{defaultHead.department}</p><p>{defaultHead.university}</p></div>
        </article>
      </div></section>
    </div>
  </main></div>;
}

