"use client";

import { useEffect, useMemo, useState } from "react";
import { emptyBill } from "../create/components/emptyBill";
import type { ExaminationBillData } from "../create/components/types";
import { loadCurrentWork } from "@/lib/storage/draft";
import { collectTeacherNames, deriveTeacherRows, rowAmount } from "../individual/individualBill";

export default function CombinedTeacherBillPage() {
  const [bill, setBill] = useState<ExaminationBillData>(emptyBill);
  useEffect(() => { const timer = window.setTimeout(() => { const saved = loadCurrentWork(); if (saved) setBill({ ...emptyBill, ...saved }); }, 0); return () => window.clearTimeout(timer); }, []);
  const teachers = useMemo(() => collectTeacherNames(bill), [bill]);
  return <main className="mx-auto max-w-5xl p-6"><div className="no-print mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Combined Teacher Bill</h1><p className="text-sm text-slate-500">Each teacher is previewed on a separate page.</p></div><button onClick={() => window.print()} className="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Print / Save Combined PDF</button></div><div className="space-y-6">{teachers.map((teacher, index) => { const rows = deriveTeacherRows(bill, teacher); const total = rows.reduce((sum, row) => sum + rowAmount(row), 0); return <article key={teacher} className="bill-page rounded-xl border bg-white p-8 shadow-sm"><h2 className="text-center text-xl font-bold">রাজশাহী প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়</h2><h3 className="mt-2 text-center font-semibold">পরীক্ষা সংক্রান্ত পারিশ্রমিকের বিল ফরম</h3><div className="mt-5 flex justify-between"><span>নামঃ {teacher}</span><span>পৃষ্ঠা: {index + 1}</span></div><table className="mt-4 w-full border-collapse text-sm"><thead><tr><th className="border p-2">ক্রমিক</th><th className="border p-2">কাজের বিবরণ</th><th className="border p-2">বিষয় / কোর্স</th><th className="border p-2">পরিমাণ</th><th className="border p-2">হার</th><th className="border p-2">টাকার পরিমাণ</th></tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={row.id}><td className="border p-2 text-center">{rowIndex + 1}</td><td className="border p-2">{row.description}</td><td className="border p-2">{row.course}</td><td className="border p-2 text-center">{row.quantity}</td><td className="border p-2 text-center">{row.rate}</td><td className="border p-2 text-right">{rowAmount(row).toLocaleString("bn-BD")}</td></tr>)}</tbody><tfoot><tr><td colSpan={5} className="border p-2 text-right font-semibold">মোটঃ</td><td className="border p-2 text-right font-bold">{total.toLocaleString("bn-BD")}</td></tr></tfoot></table><p className="mt-8">প্রতি স্বাক্ষরিত</p><div className="mt-16 flex justify-between"><span>সভাপতি, পরীক্ষা কমিটি।</span><span>পরীক্ষকের স্বাক্ষর<br/>তারিখঃ</span></div></article>; })}</div><style jsx global>{`@media print { .no-print { display:none !important } body { background:#fff !important } .bill-page { break-after: page; min-height: 250mm; border:0 !important; box-shadow:none !important; border-radius:0 !important } .bill-page:last-child { break-after:auto } }`}</style></main>;
}
